name: Deploy Infrastructure

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "infra/terraform/**"
      - ".github/workflows/deploy-infra.yml"

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  TERRAFORM_WORKING_DIR: infra/terraform

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform fmt
        run: terraform fmt -check
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}

      - name: Terraform plan
        run: terraform plan -out=tfplan
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}

      - name: Terraform apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}
