name: Deploy Inference Worker

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_ACCOUNT_ID: 894059646844
  ECS_CLUSTER_NAME: farlabs-cluster-free

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
          output-env-credentials: true

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push worker image
        env:
          IMAGE_URI: ${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/farlabs-inference-worker-free:${{ github.sha }}
          LATEST_URI: ${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/farlabs-inference-worker-free:latest
        run: |
          docker build --platform linux/amd64 -f backend/services/inference_worker/Dockerfile backend/services/inference_worker -t "$IMAGE_URI"
          docker tag "$IMAGE_URI" "$LATEST_URI"
          docker push "$IMAGE_URI"
          docker push "$LATEST_URI"

      - name: Force new deployment
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER_NAME }} \
            --service farlabs-inference-worker-free \
            --force-new-deployment \
            --region ${{ env.AWS_REGION }}
