name: Deploy Payments Service Only

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECS_CLUSTER_NAME: farlabs-cluster-free

jobs:
  deploy-payments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push payments image
        env:
          IMAGE_URI: ${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/farlabs-payments-free:${{ github.sha }}
          LATEST_URI: ${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/farlabs-payments-free:latest
        run: |
          docker build --platform linux/amd64 -f backend/services/payments/Dockerfile backend -t "$IMAGE_URI"
          docker tag "$IMAGE_URI" "$LATEST_URI"
          docker push "$IMAGE_URI"
          docker push "$LATEST_URI"

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster "${{ env.ECS_CLUSTER_NAME }}" \
            --service farlabs-payments-free \
            --force-new-deployment
